#ifndef MK1MF_BUILD
    /* auto-generated by util/mkbuildinf.pl for crypto/cversion.c */
    #define CFLAGS cflags
    /*
     * Generate CFLAGS as an array of individual characters. This is a
     * workaround for the situation where CFLAGS gets too long for a C90 string
     * literal
     */
    static const char cflags[] = {
        'c','o','m','p','i','l','e','r',':',' ','/','A','p','p','l','i','c','a',
        't','i','o','n','s','/','X','c','o','d','e','.','a','p','p','/','C','o',
        'n','t','e','n','t','s','/','D','e','v','e','l','o','p','e','r','/','T',
        'o','o','l','c','h','a','i','n','s','/','X','c','o','d','e','D','e','f',
        'a','u','l','t','.','x','c','t','o','o','l','c','h','a','i','n','/','u',
        's','r','/','b','i','n','/','c','l','a','n','g',' ','-','I','.',' ','-',
        'I','.','.',' ','-','I','.','.','/','i','n','c','l','u','d','e',' ',' ',
        '-','D','O','P','E','N','S','S','L','_','T','H','R','E','A','D','S',' ',
        '-','D','_','R','E','E','N','T','R','A','N','T',' ','-','D','D','S','O',
        '_','D','L','F','C','N',' ','-','D','H','A','V','E','_','D','L','F','C',
        'N','_','H',' ','-','a','r','c','h',' ','a','r','m','6','4',' ','-','O',
        '3',' ','-','i','s','y','s','r','o','o','t',' ','/','A','p','p','l','i',
        'c','a','t','i','o','n','s','/','X','c','o','d','e','.','a','p','p','/',
        'C','o','n','t','e','n','t','s','/','D','e','v','e','l','o','p','e','r',
        '/','P','l','a','t','f','o','r','m','s','/','i','P','h','o','n','e','O',
        'S','.','p','l','a','t','f','o','r','m','/','D','e','v','e','l','o','p',
        'e','r','/','S','D','K','s','/','i','P','h','o','n','e','O','S','.','s',
        'd','k',' ','-','m','i','p','h','o','n','e','o','s','-','v','e','r','s',
        'i','o','n','-','m','i','n','=','7','.','0',' ','-','f','o','m','i','t',
        '-','f','r','a','m','e','-','p','o','i','n','t','e','r',' ','-','f','n',
        'o','-','c','o','m','m','o','n',' ','-','f','e','m','b','e','d','-','b',
        'i','t','c','o','d','e','\0'
    };
    #define PLATFORM "platform: iphoneos-cross-arm64"
    #define DATE "built on: Fri Nov 13 15:24:35 2015"
#endif
